#!/usr/bin/env sh

apm install cobalt2-syntax
apm install linter
apm install linter-jshint
apm install linter-flake8
apm install linter-pep257
apm install linter-csslint
apm install linter-rubocop
apm install linter-coffeelint
apm install linter-rust
apm install linter-jsonlint
apm install linter-haml
apm install linter-markdown
apm install linter-reek
apm install linter-alex
apm install pigments
apm install merge-conflicts
apm install magicpython
