#!/usr/bin/env sh

# Commented parts here are with help from https:m//github.com/mathiasbynens/dotfiles
# Install GNU core utilities (those that come with OS X are outdated).
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew install coreutils
sudo ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum

# Install some other useful utilities like `sponge`.
brew install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
brew install findutils

brew install vim

brew install ack
brew install cmake
brew install git
brew install git-flow
brew install git-lfs
brew install libffi
brew install libtiff
brew install mas
brew install nvm
brew install nmap
brew install pipenv
brew install tree
brew install wget
brew install yarn
