#!/usr/bin/env sh

brew tap homebrew/versions

# Commented parts here are with help from https://github.com/mathiasbynens/dotfiles
# Install GNU core utilities (those that come with OS X are outdated).
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew install coreutils
sudo ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum

# Install some other useful utilities like `sponge`.
brew install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
brew install findutils
# Install GNU `sed`, overwriting the built-in `sed`.
brew install gnu-sed --with-default-names

# Install `wget` with IRI support.
brew install wget --with-iri

# Install more recent versions of some OS X tools.
brew install vim --override-system-vi
brew install homebrew/dupes/grep
brew install homebrew/dupes/openssh
brew install homebrew/dupes/screen

brew install ack
brew install bash
brew install bash-completion2
brew install cmake
brew install git
brew install git-flow
brew install git-lfs
brew install gpg
brew install gradle
brew install heroku-toolbelt
brew install hub
brew install leiningen
brew install libffi
brew install libtiff
brew install maven
brew install node
brew install postgresql
brew install python
brew install python3
brew install ruby
brew install sassc
brew install tomcat
brew install tree
brew install webkit2png
brew install zsh
brew install zsh-completions
