#!/usr/bin/env sh

brew install caskroom/cask/brew-cask

brew cask install amethyst
brew cask install android-studio
brew cask install arduino
brew cask install audacity
brew cask install battle-net
brew cask install blender
brew cask install discord
brew cask install dropbox
brew cask install docker
brew cask install dolphin
brew cask install etcher
brew cask install filezilla
brew cask install firefox
brew cask install font-fira-code
brew cask install gimp
brew cask install github-desktop
brew cask install google-chrome
brew cask install google-hangouts
brew cask install harvest
brew cask install insomnia
brew cask install iterm2
brew cask install minecraft
brew cask install mysqlworkbench
brew cask install ngrok
brew cask install nylas-n1
brew cask install obs
brew cask install openemu
brew cask install pomotodo
brew cask install psequel
brew cask install robo-3t
brew cask install runescape
brew cask install skype
brew cask install slack
brew cask install spectacle
brew cask install spotify
brew cask install steam
brew cask install transmission
brew cask install unity-web-player
brew cask install visual-studio-code
brew cask install xquartz
