#!/usr/bin/env sh

npm install -g alex
npm install -g bower
npm install -g grunt
npm install -g gulp
npm install -g jshint
npm install -g csslint
npm install -g coffeelint
npm install -g jsonlint
npm install -g yo
npm install -g ttystudio
npm install -g keybase
npm install -g how2
