#!/usr/bin/env sh

# from `code --list-extensions`
modules="
peterjausovec.vscode-docker
unity.unity-debug
adamvoss.yaml
bungcip.better-toml
dbaeumer.vscode-eslint
eamodio.gitlens
groksrc.haml
tobiah.unity-tools
ms-python.python
ms-vscode.cpptools
ms-vscode.csharp
ms-vscode.go
vscode-icons-team.vscode-icons
rust-lang.rust
ahmadawais.shades-of-purple
mechatroner.rainbow-csv
"
for module in $modules; do
    code --install-extension "$module" || true
done