#!/usr/bin/env sh

# Create some directories
mkdir $HOME/.install_logs/
mkdir $HOME/.vim
mkdir $HOME/.vim/swaps
mkdir $HOME/.vim/backups
mkdir $HOME/.vim/undo
mkdir $HOME/projects

# Ask for the administrator password upfront.
sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

xcode-select --install

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

sh $HOME/install
sh $HOME/manual_install

sh $HOME/config # Config System

cat $HOME/.todo

should_restart=false
should_cleanup=false

while true; do
    read -p "Clean up install scripts? " yn1
    case $yn1 in
        [yY]* ) should_cleanup=true; break;;
        [nN]* ) exit;;
        * ) echo "Please enter y/n";;
    esac
done

while true; do
    read -p "Restart computer? " yn2
    case $yn2 in
        [yY]* ) should_restart=true; break;;
        [nN]* ) exit;;
        * ) echo "Please enter y/n";;
    esac
done

if [ $should_cleanup ]
then
sudo rm -rf $HOME/config $HOME/install $HOME/manual_install
sudo rm -- $0
fi

echo "Setup Complete"

if [ $should_restart ]
then
echo "Shutting down..."
sudo shutdown -r now
fi
