#!/usr/bin/env sh

dname="Blake Grotewold"
demail="blake.grotewold@gmail.com"

read -p "Git Name ($dname): " name
read -p "Git Email ($demail): " email

git config --global user.name ${name-$dname}
git config --global user.email ${email-$demail}

ssh-keygen -t rsa -b 4096 -C ${email-$demail}
eval "$(ssh-agent -s)"
ssh-add $HOME/.ssh/id_rsa
pbcopy < $HOME/.ssh/id_rsa.pub
echo "SSH key copied."

# move .zshrc file back
rm -f $HOME/.zshrc
mv $HOME/.zshrc.pre-oh-my-zsh $HOME/.zshrc

# copy SublimeText settings
sudo -u groteworld cp -fR $HOME/.sublime/ "$HOME/Library/Application Support/Sublime Text 3/Packages/User/"

sh $HOME/.macos
