#!/usr/bin/env sh

dname="Blake Grotewold"
demail="blake.grotewold@gmail.com"

read -p "Git Name ($dname): " name
read -p "Git Email ($demail): " email

git config --global user.name ${name-$dname}
git config --global user.email ${email-$demail}

ssh-keygen -t rsa -b 4096 -C ${email-$demail}
eval "$(ssh-agent -s)"
ssh-add $HOME/.ssh/id_rsa
pbcopy < $HOME/.ssh/id_rsa.pub
echo "SSH key copied."

# move .zshrc file back
rm -f $HOME/.zshrc
mv $HOME/.zshrc.pre-oh-my-zsh $HOME/.zshrc

# copy vs-code settings
sudo -u groteworld mkdir -p "$HOME/Library/Application Support/Code/User"
sudo -u groteworld cp "$HOME/vscode/settings.json" "$HOME/Library/Application Support/Code/User/settings.json"

sh $HOME/.macos
