#!/usr/bin/env sh

sh $HOME/.packages/brew # Install Homebrew packages
sh $HOME/.packages/cask # Install Brewcask packages
sh $HOME/.packages/pip # Install PyPI packages
sh $HOME/.packages/npm # Install NPM packages
sh $HOME/.packages/gem # Install Gem packages
sh $HOME/.packages/sublime # Install SublimeText packages

wget --no-check-certificate http://install.ohmyz.sh -O - | sh
