#!/usr/bin/env sh

echo "Manual Installs"

while true; do
    echo ""
    echo "1. XCode"
    echo "2. Unity3D"
    echo "3. Textual 5"
    echo "4. iMovie"
    echo "5. GarageBand"
    echo "6. rustup"
    echo "q. exit"
    read -p "Input the number you want to open to install? " num
    case $num in
        [1] ) open macappstore://itunes.apple.com/app/id497799835?mt=12; break;;
        [2] ) brew cask install unity-download-assistant; break;;
        [3] ) open macappstore://itunes.apple.com/app/id896450579?mt=12; break;;
        [4] ) open macappstore://itunes.apple.com/app/id408981434?mt=12; break;;
        [5] ) open macappstore://itunes.apple.com/app/id682658836?mt=12; break;;
        [6] ) curl https://sh.rustup.rs -sSf | sh; break;;
        ['qQ'] ) exit;;
        * ) echo "Please enter an appropriate number or Q";;
    esac
done
